logstash-kafka-opensearch-ent

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -8,6 +8,8 @@ services:
     environment:
       ZOOKEEPER_CLIENT_PORT: 2181
       ZOOKEEPER_TICK_TIME: 2000
+    volumes:
+      - ./App-Logs/Zookeeper:/var/log/kafka
   broker:
     image: confluentinc/cp-kafka:7.0.1
     container_name: broker
@@ -56,7 +58,6 @@ services:
      - 3000:3000
     volumes:
       - ./Grafana-Storage/grafana.db:/var/lib/grafana/grafana.db
-      - ./App-Logs/Grafana:/var/log/grafana
     command: ["cd", "/usr/share/grafana/bin/", "&&", "grafana-cli", "admin", "reset-admin-password", "${GRAFANA_ADMIN_PASSWORD}"]
   prometheus:
     image: prom/prometheus
@@ -71,13 +72,20 @@ services:
       context: .
       dockerfile: ./Python-Producer/Dockerfile
     restart: always
+    volumes:
+      - ./App-Logs/Producer/producer-output.log:/usr/src/app/producer-output.log
+      - ./.env:/usr/src/app/.env
+    env_file:
+      - ./.env
+    depends_on:
+      - broker
   influxdb:
     container_name: influxdb
     image: 'influxdb:1.8'
     ports:
       - '8086:8086'
     environment:
-      INFLUXDB_DB: "${DATABASE_NAME}"
+      INFLUXDB_DB: "${INFLUXDB_DB_NAME}"
   consumer:
     container_name: consumer
     build:
@@ -87,6 +95,11 @@ services:
     depends_on:
       - influxdb
       - producer
+      - broker
+    volumes:
+      - ./.env:/usr/src/app/.env
+    env_file:
+      - ./.env
   opensearch:
     image: opensearchproject/opensearch
     container_name: opensearch
@@ -95,7 +108,6 @@ services:
       - node.name=opensearch-node
       - bootstrap.memory_lock=true
       - discovery.type=single-node
-      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
       - discovery.type=single-node
     ulimits:
       memlock:
@@ -129,12 +141,24 @@ services:
     ports:
       - "5044:5044"
     volumes:
-      - ./Logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
-      - ./Logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
-      - ./Logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
-      - ./Logstash/logstash-sample.conf:/usr/share/logstash/config/logstash-sample.conf
-      - ./App-Logs/Broker:/shared-logs
+      - ./Logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
+      - ./Logstash/config//pipelines.yml:/usr/share/logstash/config/pipelines.yml
+      - ./Logstash/config/logstash-broker.conf:/usr/share/logstash/config/logstash-broker.conf
+      - ./Logstash/config/logstash-zookeeper.conf:/usr/share/logstash/config/logstash-zookeeper.conf
+      - ./Logstash/config/logstash-producer.conf:/usr/share/logstash/config/logstash-producer.conf
+      - ./App-Logs:/shared-logs
     environment:
       LS_JAVA_OPTS: -Xms1g -Xmx1g
       OPENSEARCH_HOST: opensearch:9200
-    command: sh -c "bin/logstash-plugin install logstash-output-opensearch && logstash"
+    entrypoint: >
+      bash -c "
+
+      if ! bin/logstash-plugin list --verbose | grep -q 'logstash-output-opensearch'; then
+        echo 'logstash-output-opensearch plugin not found. Installing...';
+        echo 'this will approximately take 5 minutes depending on your machine.'
+        bin/logstash-plugin install logstash-output-opensearch;
+      else
+        echo 'logstash-output-opensearch plugin is already installed.';
+      fi
+      
+      bin/logstash"
